/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework;

/**
 *
 * @author joyes
 */
public class Homework05_汽車價錢計算 extends javax.swing.JFrame {

    /**
     * Creates new form Work08_汽車價錢計算
     */
    public Homework05_汽車價錢計算() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        rdo跑車 = new javax.swing.JRadioButton();
        rdo轎車豪華型 = new javax.swing.JRadioButton();
        rdo轎車經濟型 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        chkCD音響 = new javax.swing.JCheckBox();
        chk天窗 = new javax.swing.JCheckBox();
        chk自動排檔 = new javax.swing.JCheckBox();
        lbl金額 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("汽車價錢計算");

        buttonGroup1.add(rdo跑車);
        rdo跑車.setText("跑車");
        rdo跑車.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                汽車價錢計算(evt);
            }
        });

        buttonGroup1.add(rdo轎車豪華型);
        rdo轎車豪華型.setText("轎車(豪華型)");
        rdo轎車豪華型.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                汽車價錢計算(evt);
            }
        });

        buttonGroup1.add(rdo轎車經濟型);
        rdo轎車經濟型.setText("轎車(經濟型)");
        rdo轎車經濟型.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                汽車價錢計算(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo跑車)
                    .addComponent(rdo轎車豪華型)
                    .addComponent(rdo轎車經濟型))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rdo跑車)
                .addGap(18, 18, 18)
                .addComponent(rdo轎車豪華型)
                .addGap(18, 18, 18)
                .addComponent(rdo轎車經濟型)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        chkCD音響.setText("CD音響");
        chkCD音響.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                汽車價錢計算(evt);
            }
        });

        chk天窗.setText("天窗");
        chk天窗.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                汽車價錢計算(evt);
            }
        });

        chk自動排檔.setText("自動排檔");
        chk自動排檔.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                汽車價錢計算(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk天窗)
                    .addComponent(chk自動排檔)
                    .addComponent(chkCD音響))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(chkCD音響)
                .addGap(18, 18, 18)
                .addComponent(chk天窗)
                .addGap(18, 18, 18)
                .addComponent(chk自動排檔)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        lbl金額.setBackground(new java.awt.Color(51, 255, 153));
        lbl金額.setFont(new java.awt.Font("新細明體", 1, 24)); // NOI18N
        lbl金額.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl金額, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl金額, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 汽車價錢計算(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_汽車價錢計算
      
        int money = 0, money2 = 0, money3 = 0, money4 = 0, sum = 0;

        if (rdo跑車.isSelected()) {
            money = 800000;
        } else if (rdo轎車豪華型.isSelected()) {
            money = 650000;
        } else if (rdo轎車經濟型.isSelected()) {
            money = 450000;
        }

        money2 = (chkCD音響.isSelected()) ? 4000 : 0;
        money3 = (chk天窗.isSelected()) ? 5000 : 0;
        money4 = (chk自動排檔.isSelected()) ? 3000 : 0;

        sum = money + money2 + money3 + money4;
        lbl金額.setText(String.valueOf(sum));
    }//GEN-LAST:event_汽車價錢計算

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homework05_汽車價錢計算.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homework05_汽車價錢計算.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homework05_汽車價錢計算.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homework05_汽車價錢計算.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homework05_汽車價錢計算().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkCD音響;
    private javax.swing.JCheckBox chk天窗;
    private javax.swing.JCheckBox chk自動排檔;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lbl金額;
    private javax.swing.JRadioButton rdo跑車;
    private javax.swing.JRadioButton rdo轎車經濟型;
    private javax.swing.JRadioButton rdo轎車豪華型;
    // End of variables declaration//GEN-END:variables
}
