/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Homework;

import javax.swing.JButton;

/**
 *
 * @author joyes
 */
public class Homework08_計算機 extends javax.swing.JFrame {

    public boolean ok = false;
    public int x;
    public int y;
    public String op = "";

    public Homework08_計算機() {
        initComponents();
        txt1.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btnmult = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btnresult = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("計算機");

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                計算(evt);
            }
        });

        btnclear.setText("C");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                歸零(evt);
            }
        });

        btnsub.setText("-");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                計算(evt);
            }
        });

        btnmult.setText("*");
        btnmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                計算(evt);
            }
        });

        btndiv.setText("/");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                計算(evt);
            }
        });

        btnresult.setText("=");
        btnresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                結果(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btnback.setText("<--");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                刪除(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(btn6)
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn1)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn2)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn4)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn7)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn8)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn0)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnback)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnresult)))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btndiv)
                                .addComponent(btnmult)
                                .addComponent(btnsub)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnadd)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnclear)))))
                    .addContainerGap(109, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(btn6)
                .addGap(177, 177, 177))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1)
                        .addComponent(btn2)
                        .addComponent(btn3)
                        .addComponent(btnadd)
                        .addComponent(btnclear))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4)
                        .addComponent(btn5)
                        .addComponent(btnsub))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn7)
                        .addComponent(btn8)
                        .addComponent(btn9)
                        .addComponent(btnmult))
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0)
                        .addComponent(btnback)
                        .addComponent(btnresult)
                        .addComponent(btndiv))
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 數字(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_數字
        JButton btn = (JButton) evt.getSource();
        if (txt1.getText().equals("0")) {
            txt1.setText("");
        }
        //ok 前面先設 false
        //只能做一次 ==>所以用 布林值控制
        if ((op.equals("+") || op.equals("-") || op.equals("*") || op.equals("/")) && !ok) {
            txt1.setText("");
            ok = true; //做完後馬上設為 true ==>表示 第 二次按數字後 不能再做這一段
        }

        txt1.setText(txt1.getText() + btn.getText());
    }//GEN-LAST:event_數字

    private void 刪除(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_刪除
        int len;
        len = txt1.getText().length();

        if (len != 0) {
            String str = txt1.getText().substring(0, len - 1);
            txt1.setText(str);
            if (txt1.getText().length() == 0) {
                txt1.setText("0");
            }
        }
    }//GEN-LAST:event_刪除

    private void 結果(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_結果
        y = Integer.parseInt(txt1.getText());
        double sum1 = 0.0;
        int sum2 = 0;
        switch (op) {
            case "+":
                sum2 = (x + y);
                txt1.setText(String.valueOf(sum2));
                break;
            case "-":
                sum2 = x - y;
                txt1.setText(String.valueOf(sum2));
                break;
            case "*":
                sum2 = x * y;
                txt1.setText(String.valueOf(sum2));
                break;
            case "/":
                sum1 = (double) x / y;
                txt1.setText(String.valueOf(sum1));
                break;
        }
        //計算完結果後 ,x, ok 與 op 要回歸正常
        x = 0;
        y = 0;
        ok = false;
        op = "";
    }//GEN-LAST:event_結果

    private void 計算(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_計算
        JButton btn = (JButton) evt.getSource();
        x = Integer.parseInt(txt1.getText());
        op = btn.getText();
    }//GEN-LAST:event_計算

    private void 歸零(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_歸零
        txt1.setText("0");
    }//GEN-LAST:event_歸零

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homework08_計算機.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homework08_計算機.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homework08_計算機.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homework08_計算機.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homework08_計算機().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnmult;
    private javax.swing.JButton btnresult;
    private javax.swing.JButton btnsub;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
