/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package winJFrame;

/**
 *
 * @author joyes
 */
public class Frame02_05BoxLayout2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame253
     */
    public Frame02_05BoxLayout2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP3 = new javax.swing.JPanel();
        North0 = new javax.swing.JButton();
        North1 = new javax.swing.JButton();
        North2 = new javax.swing.JButton();
        North3 = new javax.swing.JButton();
        North4 = new javax.swing.JButton();
        JP2 = new javax.swing.JPanel();
        East0 = new javax.swing.JButton();
        East1 = new javax.swing.JButton();
        East2 = new javax.swing.JButton();
        East3 = new javax.swing.JButton();
        East4 = new javax.swing.JButton();
        JP4 = new javax.swing.JPanel();
        South0 = new javax.swing.JButton();
        South1 = new javax.swing.JButton();
        South2 = new javax.swing.JButton();
        South3 = new javax.swing.JButton();
        South4 = new javax.swing.JButton();
        JP1 = new javax.swing.JPanel();
        West0 = new javax.swing.JButton();
        West1 = new javax.swing.JButton();
        West2 = new javax.swing.JButton();
        West3 = new javax.swing.JButton();
        West4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 100, 500, 400));

        JP3.setLayout(new javax.swing.BoxLayout(JP3, javax.swing.BoxLayout.LINE_AXIS));

        North0.setText("North0");
        JP3.add(North0);

        North1.setText("North1");
        JP3.add(North1);

        North2.setText("North2");
        JP3.add(North2);

        North3.setText("North3");
        JP3.add(North3);

        North4.setText("North4");
        JP3.add(North4);

        getContentPane().add(JP3, java.awt.BorderLayout.NORTH);

        JP2.setLayout(new javax.swing.BoxLayout(JP2, javax.swing.BoxLayout.Y_AXIS));

        East0.setText("East0");
        JP2.add(East0);

        East1.setText("East1");
        JP2.add(East1);

        East2.setText("East2");
        JP2.add(East2);

        East3.setText("East3");
        JP2.add(East3);

        East4.setText("East4");
        JP2.add(East4);

        getContentPane().add(JP2, java.awt.BorderLayout.EAST);

        JP4.setLayout(new javax.swing.BoxLayout(JP4, javax.swing.BoxLayout.LINE_AXIS));

        South0.setText("South0");
        JP4.add(South0);

        South1.setText("South1");
        JP4.add(South1);

        South2.setText("South2");
        JP4.add(South2);

        South3.setText("South3");
        JP4.add(South3);

        South4.setText("South4");
        JP4.add(South4);

        getContentPane().add(JP4, java.awt.BorderLayout.SOUTH);

        JP1.setLayout(new javax.swing.BoxLayout(JP1, javax.swing.BoxLayout.Y_AXIS));

        West0.setText("West0");
        JP1.add(West0);

        West1.setText("West1");
        JP1.add(West1);

        West2.setText("West2");
        JP1.add(West2);

        West3.setText("West3");
        JP1.add(West3);

        West4.setText("West4");
        JP1.add(West4);

        getContentPane().add(JP1, java.awt.BorderLayout.WEST);

        setBounds(0, 0, 466, 398);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame02_05BoxLayout2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame02_05BoxLayout2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame02_05BoxLayout2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame02_05BoxLayout2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame02_05BoxLayout2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton East0;
    private javax.swing.JButton East1;
    private javax.swing.JButton East2;
    private javax.swing.JButton East3;
    private javax.swing.JButton East4;
    private javax.swing.JPanel JP1;
    private javax.swing.JPanel JP2;
    private javax.swing.JPanel JP3;
    private javax.swing.JPanel JP4;
    private javax.swing.JButton North0;
    private javax.swing.JButton North1;
    private javax.swing.JButton North2;
    private javax.swing.JButton North3;
    private javax.swing.JButton North4;
    private javax.swing.JButton South0;
    private javax.swing.JButton South1;
    private javax.swing.JButton South2;
    private javax.swing.JButton South3;
    private javax.swing.JButton South4;
    private javax.swing.JButton West0;
    private javax.swing.JButton West1;
    private javax.swing.JButton West2;
    private javax.swing.JButton West3;
    private javax.swing.JButton West4;
    // End of variables declaration//GEN-END:variables
}
